- name: app setup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-setup

- name: maven setup
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: import data
  tags:
  - import
  community.mysql.mysql_db:
    login_user: root
    login_password: RoboShop@1    
    login_host: mysql.shaik.fun
    name: all
    state: import
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql  

- name: systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd