- name: app setup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-setup

- name: python setup
  ansible.builtin.include_role:
    name: common
    tasks_from: python

- name: systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd
