- name: copy rabbitmq repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo


- name: install rabbitmq server
  ansible.builtin.dnf:
    name: rebbitmq-server
    state: installed

- name: start and enable rabbitmq-server
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

# rabbitmq comes with a default user. we can't use this user to connet. So we are creating a user for the application
- name: create a user for the application
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present


    