- name: app setup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-setup 

- name: nodejs setup
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: copy mongo repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb clients
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: connect to mongodb server to check data is loaded or not
  ansible.builtin.command: mongosh --host catalogue.shaik.fun --eval 'db.getMongo().getDBNames().indexOf("catalogue")'   
  register: catalogue_output

- name: print he catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"  

- name: load the products data into database     
  ansible.builtin.command: mongosh --host catalogue.shaik.fun  </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd


