- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: create roboshop system user
  ansible.builtin.user:
    system: true
    name: roboshop
    shell: /sbin/nologin
    home: /app
    comment: "roboshop system user"   

- name: download app code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/"{{ component }}"-v3.zip
    dest: /tmp/"{{ component }}".zip

- name: unzip the app code
  ansible.builtin.unarchive:
    src: /tmp/"{{ component }}".zip
    dest: /app
    remote_src: yes
    