- name: install maven and mysql 
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql

# to connect with mysql database ansible requires few python packages to connect to the database which are pymysql and cryptography. we install those packages using python package manager which is pip
- name: install PyMySQL and cryptography
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.13
  loop:
  - PyMySQL
  - cryptography


- name: install  maven dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app                        
    

- name: change file name
  ansible.builtin.command:   mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app